/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

import static com.mycompany.mavenproject1.NewMain.socket;
import io.socket.client.IO;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Yan
 */
public class panelDeInicio extends javax.swing.JFrame {

    /**
     * Creates new form panelDeInicio
     */
    public panelDeInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnPantalla1 = new javax.swing.JButton();
        btnPantalla2 = new javax.swing.JButton();
        btnPantalla3 = new javax.swing.JButton();
        btnPantalla4 = new javax.swing.JButton();
        btnPantalla5 = new javax.swing.JButton();
        btnPantalla6 = new javax.swing.JButton();
        btnPantalla7 = new javax.swing.JButton();
        btnPantalla8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("IP SERVIDOR:");

        jTextField1.setText("159.65.104.236:3001");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Funcion");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPantalla1.setText("Pantalla 1");
        btnPantalla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla1ActionPerformed(evt);
            }
        });

        btnPantalla2.setText("Pantalla 2");
        btnPantalla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla2ActionPerformed(evt);
            }
        });

        btnPantalla3.setText("Pantalla 3");
        btnPantalla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla3ActionPerformed(evt);
            }
        });

        btnPantalla4.setText("Pantalla 4");
        btnPantalla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla4ActionPerformed(evt);
            }
        });

        btnPantalla5.setText("Pantalla 5");
        btnPantalla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla5ActionPerformed(evt);
            }
        });

        btnPantalla6.setText("Pantalla 6");
        btnPantalla6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla6ActionPerformed(evt);
            }
        });

        btnPantalla7.setText("Pantalla 7");
        btnPantalla7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla7ActionPerformed(evt);
            }
        });

        btnPantalla8.setText("Pantalla 8");
        btnPantalla8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPantalla1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPantalla2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPantalla3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPantalla4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPantalla5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPantalla6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPantalla7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPantalla8)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPantalla1)
                    .addComponent(btnPantalla2)
                    .addComponent(btnPantalla3))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPantalla4)
                    .addComponent(btnPantalla5)
                    .addComponent(btnPantalla6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPantalla7)
                    .addComponent(btnPantalla8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        switch(0){
            case 0:
                pantalla1 p=new pantalla1();
                p.setVisible(true);
            case 1:
                pantalla2 p2=new pantalla2();
                p2.setVisible(true);
            case 2:
                pantalla3 p3=new pantalla3();
                p3.setVisible(true);
            case 3:
                pantalla4 p4=new pantalla4();
                p4.setVisible(true);
            case 4:
                pantalla5 p5=new pantalla5();
                p5.setVisible(true);
            case 5:
                pantalla6 p6=new pantalla6();
                p6.setVisible(true);
            case 6:
                pantalla7 p7=new pantalla7();
                p7.setVisible(true);
        }

//                empezar e=new empezar();
//                e.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPantalla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla1ActionPerformed
        pantalla1 p1=new pantalla1();
        p1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla1ActionPerformed

    private void btnPantalla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla2ActionPerformed
        pantalla2 p2=new pantalla2();
        p2.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla2ActionPerformed

    private void btnPantalla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla3ActionPerformed
        pantalla3 p3=new pantalla3();
        p3.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla3ActionPerformed

    private void btnPantalla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla4ActionPerformed
        pantalla4 p4=new pantalla4();
        p4.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla4ActionPerformed

    private void btnPantalla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla5ActionPerformed
        pantalla5 p5=new pantalla5();
        p5.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla5ActionPerformed

    private void btnPantalla6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla6ActionPerformed
        pantalla6 p6=new pantalla6();
        p6.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla6ActionPerformed

    private void btnPantalla7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla7ActionPerformed
        pantalla7 p7=new pantalla7();
        p7.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla7ActionPerformed

    private void btnPantalla8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPantalla8ActionPerformed

    private class empezar extends Thread{   
        public void run(){
            int n=2000;
            try {
            pantalla1 p=new pantalla1();
            p.setVisible(true);
            Thread.sleep(n);
            pantalla2 p2=new pantalla2();
            p2.setVisible(true);
            Thread.sleep(n);
            pantalla3 p3=new pantalla3();
            p3.setVisible(true);
            Thread.sleep(n);
            pantalla4 p4=new pantalla4();
            p4.setVisible(true);
            Thread.sleep(n);
            pantalla5 p5=new pantalla5();
            p5.setVisible(true);
            Thread.sleep(n);
            pantalla6 p6=new pantalla6();
            p6.setVisible(true);
            Thread.sleep(n);
            pantalla7 p7=new pantalla7();
            p7.setVisible(true);
            Thread.sleep(n);
            } catch (InterruptedException ex) {
                Logger.getLogger(panelDeInicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
        }
    }
                    
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelDeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelDeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelDeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelDeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelDeInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPantalla1;
    private javax.swing.JButton btnPantalla2;
    private javax.swing.JButton btnPantalla3;
    private javax.swing.JButton btnPantalla4;
    private javax.swing.JButton btnPantalla5;
    private javax.swing.JButton btnPantalla6;
    private javax.swing.JButton btnPantalla7;
    private javax.swing.JButton btnPantalla8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
