/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

import static com.mycompany.mavenproject1.NewMain.socket;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yan
 */
public class panelDeInicio extends javax.swing.JFrame {

    /**
     * Creates new form panelDeInicio
     */
    public panelDeInicio() {
        initComponents();
        setTitle("Simulacion mineria a cielo abierto");
        setExtendedState(this.MAXIMIZED_BOTH);
        
//        empezar h=new empezar();
//        h.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPantalla1 = new javax.swing.JButton();
        btnPantalla2 = new javax.swing.JButton();
        btnPantalla3 = new javax.swing.JButton();
        btnPantalla4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("IP SERVIDOR:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setText("159.65.104.236:3001");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Funcion");

        btnPantalla1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPantalla1.setText("Pantalla 1");
        btnPantalla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla1ActionPerformed(evt);
            }
        });

        btnPantalla2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPantalla2.setText("Pantalla 2");
        btnPantalla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla2ActionPerformed(evt);
            }
        });

        btnPantalla3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPantalla3.setText("Pantalla 3");
        btnPantalla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla3ActionPerformed(evt);
            }
        });

        btnPantalla4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPantalla4.setText("Pantalla 4");
        btnPantalla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalla4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPantalla1)
                        .addGap(22, 22, 22)
                        .addComponent(btnPantalla2)
                        .addGap(18, 18, 18)
                        .addComponent(btnPantalla3)
                        .addGap(18, 18, 18)
                        .addComponent(btnPantalla4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPantalla1)
                    .addComponent(btnPantalla2)
                    .addComponent(btnPantalla3)
                    .addComponent(btnPantalla4))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnPantalla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla1ActionPerformed
        pantalla2 p2=new pantalla2();
        p2.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla1ActionPerformed

    private void btnPantalla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla2ActionPerformed
        pantalla3 p3=new pantalla3();
        p3.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla2ActionPerformed

    private void btnPantalla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla3ActionPerformed
        pantalla7 p7=new pantalla7();
        p7.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla3ActionPerformed

    private void btnPantalla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalla4ActionPerformed
        pantalla4 p4=new pantalla4();
        p4.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPantalla4ActionPerformed

    private class empezar extends Thread{   
        public void run(){
            int n=2000;
            try {
            pantalla1 p=new pantalla1();
            p.setVisible(true);
            Thread.sleep(n);
            pantalla2 p2=new pantalla2();
            p2.setVisible(true);
            Thread.sleep(n);
            pantalla3 p3=new pantalla3();
            p3.setVisible(true);
            Thread.sleep(n);
            pantalla4 p4=new pantalla4();
            p4.setVisible(true);
            Thread.sleep(n*2);
            pantalla5 p5=new pantalla5();
            p5.setVisible(true);
            Thread.sleep(n*2);
            pantalla6 p6=new pantalla6();
            p6.setVisible(true);
            Thread.sleep(n*2);
            pantalla7 p7=new pantalla7();
            p7.setVisible(true);
            Thread.sleep(n);
            } catch (InterruptedException ex) {
                System.out.println(ex);
            }
            dispose();
        }
    }
                    
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelDeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelDeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelDeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelDeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelDeInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPantalla1;
    private javax.swing.JButton btnPantalla2;
    private javax.swing.JButton btnPantalla3;
    private javax.swing.JButton btnPantalla4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
